#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
#ifndef JOINSTORIESSDK_SWIFT_H
#define JOINSTORIESSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="JoinStoriesSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;

SWIFT_CLASS("_TtC14JoinStoriesSDK17JoinConfiguration")
@interface JoinConfiguration : NSObject
- (nonnull instancetype)initWithTeam:(NSString * _Nonnull)team OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14JoinStoriesSDK11JoinStories")
@interface JoinStories : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) JoinStories * _Nonnull shared;)
+ (JoinStories * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (void)setConfiguration:(JoinConfiguration * _Nonnull)configuration;
+ (void)stopPlayer;
- (void)stopPlayer;
@end

@class UIColor;
enum PlayerVerticalAnchor : NSInteger;

SWIFT_PROTOCOL("_TtP14JoinStoriesSDK17JoinStoriesConfig_")
@protocol JoinStoriesConfig
@property (nonatomic, copy) NSString * _Nonnull alias;
@property (nonatomic) NSTimeInterval requestTimeoutInterval;
@property (nonatomic, strong) UIColor * _Nonnull playerBackgroundColor;
@property (nonatomic) enum PlayerVerticalAnchor playerVerticalAnchor;
@property (nonatomic) BOOL playerShowShareButton;
@property (nonatomic) NSInteger playerHorizontalMargins;
@property (nonatomic) NSInteger playerCornerRadius;
@property (nonatomic, copy) NSString * _Nullable playerProgressBarDefaultColor;
@property (nonatomic, copy) NSString * _Nullable playerProgressBarFillColor;
@property (nonatomic) NSInteger playerProgressBarThickness;
@property (nonatomic) NSInteger playerProgressBarRadius;
@end

enum PlayerStandaloneAnimationOrigin : NSInteger;

SWIFT_CLASS("_TtC14JoinStoriesSDK27JoinStoriesStandaloneConfig")
@interface JoinStoriesStandaloneConfig : NSObject <JoinStoriesConfig>
@property (nonatomic, copy) NSString * _Nonnull alias;
@property (nonatomic) NSTimeInterval requestTimeoutInterval;
@property (nonatomic, strong) UIColor * _Nonnull playerBackgroundColor;
@property (nonatomic) enum PlayerVerticalAnchor playerVerticalAnchor;
@property (nonatomic) BOOL playerShowShareButton;
@property (nonatomic) NSInteger playerHorizontalMargins;
@property (nonatomic) NSInteger playerCornerRadius;
@property (nonatomic, copy) NSString * _Nullable playerProgressBarDefaultColor;
@property (nonatomic, copy) NSString * _Nullable playerProgressBarFillColor;
@property (nonatomic) NSInteger playerProgressBarThickness;
@property (nonatomic) NSInteger playerProgressBarRadius;
- (nonnull instancetype)initWithAlias:(NSString * _Nonnull)alias requestTimeoutInterval:(NSTimeInterval)requestTimeoutInterval playerBackgroundColor:(UIColor * _Nonnull)playerBackgroundColor playerStandaloneAnimationOrigin:(enum PlayerStandaloneAnimationOrigin)playerStandaloneAnimationOrigin playerVerticalAnchor:(enum PlayerVerticalAnchor)playerVerticalAnchor playerShowShareButton:(BOOL)playerShowShareButton playerHorizontalMargins:(NSInteger)playerHorizontalMargins playerCornerRadius:(NSInteger)playerCornerRadius playerProgressBarDefaultColor:(NSString * _Nullable)playerProgressBarDefaultColor playerProgressBarFillColor:(NSString * _Nullable)playerProgressBarFillColor playerProgressBarThickness:(NSInteger)playerProgressBarThickness playerProgressBarRadius:(NSInteger)playerProgressBarRadius OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14JoinStoriesSDK34JoinStoriesStandaloneDefaultConfig")
@interface JoinStoriesStandaloneDefaultConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) JoinStoriesStandaloneDefaultConfig * _Nonnull shared;)
+ (JoinStoriesStandaloneDefaultConfig * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14JoinStoriesSDK22JoinStoriesThumbConfig")
@interface JoinStoriesThumbConfig : NSObject <JoinStoriesConfig>
@property (nonatomic, copy) NSString * _Nonnull alias;
@property (nonatomic) NSTimeInterval requestTimeoutInterval;
@property (nonatomic, strong) UIColor * _Nonnull playerBackgroundColor;
@property (nonatomic) enum PlayerVerticalAnchor playerVerticalAnchor;
@property (nonatomic) BOOL playerShowShareButton;
@property (nonatomic) NSInteger playerHorizontalMargins;
@property (nonatomic) NSInteger playerCornerRadius;
@property (nonatomic, copy) NSString * _Nullable playerProgressBarDefaultColor;
@property (nonatomic, copy) NSString * _Nullable playerProgressBarFillColor;
@property (nonatomic) NSInteger playerProgressBarThickness;
@property (nonatomic) NSInteger playerProgressBarRadius;
- (nonnull instancetype)initWithAlias:(NSString * _Nonnull)alias requestTimeoutInterval:(NSTimeInterval)requestTimeoutInterval containerDimension:(NSInteger)containerDimension fontName:(NSString * _Nonnull)fontName labelColor:(UIColor * _Nonnull)labelColor thumbViewSpacing:(NSInteger)thumbViewSpacing withLabel:(BOOL)withLabel loaderInnerViewColor:(NSArray<UIColor *> * _Nonnull)loaderInnerViewColor loaderColors:(NSArray<UIColor *> * _Nonnull)loaderColors loaderInnerViewWidth:(NSInteger)loaderInnerViewWidth loaderWidth:(NSInteger)loaderWidth storyViewedIndicatorColor:(UIColor * _Nonnull)storyViewedIndicatorColor storyViewedIndicatorAlpha:(float)storyViewedIndicatorAlpha thumbViewOverlayColor:(UIColor * _Nonnull)thumbViewOverlayColor playerBackgroundColor:(UIColor * _Nonnull)playerBackgroundColor playerVerticalAnchor:(enum PlayerVerticalAnchor)playerVerticalAnchor playerShowShareButton:(BOOL)playerShowShareButton playerHorizontalMargins:(NSInteger)playerHorizontalMargins playerCornerRadius:(NSInteger)playerCornerRadius playerProgressBarDefaultColor:(NSString * _Nullable)playerProgressBarDefaultColor playerProgressBarFillColor:(NSString * _Nullable)playerProgressBarFillColor playerProgressBarThickness:(NSInteger)playerProgressBarThickness playerProgressBarRadius:(NSInteger)playerProgressBarRadius OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM(NSInteger, PlayerStandaloneAnimationOrigin, open) {
  PlayerStandaloneAnimationOriginDefault = 0,
  PlayerStandaloneAnimationOriginTop = 1,
  PlayerStandaloneAnimationOriginTopLeft = 2,
  PlayerStandaloneAnimationOriginTopRight = 3,
  PlayerStandaloneAnimationOriginBottom = 4,
  PlayerStandaloneAnimationOriginBottomLeft = 5,
  PlayerStandaloneAnimationOriginBottomRight = 6,
};

typedef SWIFT_ENUM(NSInteger, PlayerVerticalAnchor, open) {
/// Anchor is expanded out of its safe area.
  PlayerVerticalAnchorTopIgnoringSafeArea = 0,
/// Anchor is considering its safe area.
  PlayerVerticalAnchorTopWithSafeArea = 1,
  PlayerVerticalAnchorBottom = 2,
  PlayerVerticalAnchorCenter = 3,
};

typedef SWIFT_ENUM(NSInteger, StoriesAPIError, open) {
  StoriesAPIErrorConfigurationNotFound = 0,
  StoriesAPIErrorConfigurationNoTeamFound = 1,
  StoriesAPIErrorNoData = 2,
  StoriesAPIErrorFetchingStoriesTimedOut = 3,
  StoriesAPIErrorFetchingStoriesFailed = 4,
  StoriesAPIErrorFetchingStoriesEmpty = 5,
};
static NSString * _Nonnull const StoriesAPIErrorDomain = @"JoinStoriesSDK.StoriesAPIError";


SWIFT_CLASS("_TtC14JoinStoriesSDK34StoryCircularInteractiveTransition")
@interface StoryCircularInteractiveTransition : UIPercentDrivenInteractiveTransition
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14JoinStoriesSDK23StoryCircularTransition")
@interface StoryCircularTransition : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol UIViewControllerContextTransitioning;

@interface StoryCircularTransition (SWIFT_EXTENSION(JoinStoriesSDK)) <UIViewControllerAnimatedTransitioning>
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> _Nullable)transitionContext SWIFT_WARN_UNUSED_RESULT;
- (void)animateTransition:(id <UIViewControllerContextTransitioning> _Nonnull)transitionContext;
@end

@class NSCoder;

SWIFT_CLASS("_TtC14JoinStoriesSDK23StoryCollectionViewCell")
@interface StoryCollectionViewCell : UICollectionViewCell
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForReuse;
@end

@class NSIndexPath;

SWIFT_PROTOCOL("_TtP14JoinStoriesSDK23StoryNavigationDelegate_")
@protocol StoryNavigationDelegate
/// Save as <code>seen</code> when navigating through stories
- (void)storyItemShownAt:(NSIndexPath * _Nonnull)indexPath;
@end

@class WKWebViewConfiguration;
@class WKUserContentController;
@class WKScriptMessage;

SWIFT_CLASS("_TtC14JoinStoriesSDK11StoryPlayer")
@interface StoryPlayer : WKWebView <WKScriptMessageHandler>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end



@class WKNavigation;
@class WKNavigationAction;
@class UIScrollView;
@class StoryValue;
@class NSBundle;

SWIFT_CLASS("_TtC14JoinStoriesSDK25StoryPlayerViewController")
@interface StoryPlayerViewController : UIViewController <WKNavigationDelegate>
@property (nonatomic) CGPoint startingPoint;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)onPlayerDismiss;
- (void)didReceiveNoPreviousPageListenerOn:(StoryValue * _Nonnull)story;
- (void)didReceiveNoNextPageListenerOn:(StoryValue * _Nonnull)story;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface StoryPlayerViewController (SWIFT_EXTENSION(JoinStoriesSDK)) <UIViewControllerTransitioningDelegate>
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed SWIFT_WARN_UNUSED_RESULT;
@end

@class UICollectionView;

@interface StoryPlayerViewController (SWIFT_EXTENSION(JoinStoriesSDK)) <UICollectionViewDataSource>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class UICollectionViewLayout;

@interface StoryPlayerViewController (SWIFT_EXTENSION(JoinStoriesSDK)) <UICollectionViewDelegateFlowLayout>
- (void)collectionView:(UICollectionView * _Nonnull)collectionView willDisplayCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


/// This class will inherit from NSObject and will implement the
/// UIViewControllerAnimatedTransitioning protocol for the transition from top to bottom
SWIFT_CLASS("_TtC14JoinStoriesSDK24StorySlideDownTransition")
@interface StorySlideDownTransition : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface StorySlideDownTransition (SWIFT_EXTENSION(JoinStoriesSDK)) <UIViewControllerAnimatedTransitioning>
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> _Nullable)transitionContext SWIFT_WARN_UNUSED_RESULT;
- (void)animateTransition:(id <UIViewControllerContextTransitioning> _Nonnull)transitionContext;
@end


/// This class will inherit from NSObject and will implement the
/// UIViewControllerAnimatedTransitioning protocol for the transition from bottom to top
SWIFT_CLASS("_TtC14JoinStoriesSDK22StorySlideUpTransition")
@interface StorySlideUpTransition : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface StorySlideUpTransition (SWIFT_EXTENSION(JoinStoriesSDK)) <UIViewControllerTransitioningDelegate>
@end


@interface StorySlideUpTransition (SWIFT_EXTENSION(JoinStoriesSDK)) <UIViewControllerAnimatedTransitioning>
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> _Nullable)transitionContext SWIFT_WARN_UNUSED_RESULT;
- (void)animateTransition:(id <UIViewControllerContextTransitioning> _Nonnull)transitionContext;
@end


SWIFT_CLASS("_TtC14JoinStoriesSDK14StoryThumbView")
@interface StoryThumbView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end



/// Used for custom transition
/// Implement UIViewControllerTransitioningDelegate`
/// See https://developer.apple.com/documentation/uikit/animation_and_haptics/view_controller_transitions
SWIFT_CLASS("_TtC14JoinStoriesSDK29StoryTransitionViewController")
@interface StoryTransitionViewController : UIViewController
/// Stories array to display
@property (nonatomic, copy) NSArray<StoryValue *> * _Nonnull stories;
/// Transition when displaying stories
/// Implement animations for our class
/// Conforms to <code>UIViewControllerAnimatedTransitioning</code> protocol
/// See https://developer.apple.com/documentation/uikit/uiviewcontrolleranimatedtransitioning
@property (nonatomic, strong) StoryCircularTransition * _Nonnull transition;
/// Interactive Transition when displaying stories
/// Inherits from <code>UIPercentDrivenInteractiveTransition</code>
/// See https://developer.apple.com/documentation/uikit/uipercentdriveninteractivetransition
@property (nonatomic, strong) StoryCircularInteractiveTransition * _Nonnull interactiveTransition;
/// StartingPoint from where the transition begins
/// With CollectionView, startingPoint correspond to center of the <code>collectionViewCell</code>
@property (nonatomic) CGPoint startingPoint;
/// CollectionView used to display thumbnails
/// Init CollectionView with <code>collectionViewLayout</code> and register to <code>StoryCollectionViewCell</code>
/// Should implement <code>UICollectionViewDelegate</code>
@property (nonatomic, strong) UICollectionView * _Nonnull collectionView;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@interface StoryTransitionViewController (SWIFT_EXTENSION(JoinStoriesSDK)) <StoryNavigationDelegate>
- (void)storyItemShownAt:(NSIndexPath * _Nonnull)indexPath;
@end


@interface StoryTransitionViewController (SWIFT_EXTENSION(JoinStoriesSDK)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@protocol UIViewControllerInteractiveTransitioning;

@interface StoryTransitionViewController (SWIFT_EXTENSION(JoinStoriesSDK)) <UIViewControllerTransitioningDelegate>
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerInteractiveTransitioning> _Nullable)interactionControllerForDismissal:(id <UIViewControllerAnimatedTransitioning> _Nonnull)animator SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14JoinStoriesSDK10StoryValue")
@interface StoryValue : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14JoinStoriesSDK15StoryViewConfig")
@interface StoryViewConfig : NSObject
- (nonnull instancetype)initWithRequestTimeoutInterval:(NSTimeInterval)requestTimeoutInterval containerDimension:(NSInteger)containerDimension fontName:(NSString * _Nonnull)fontName labelColor:(UIColor * _Nonnull)labelColor thumbViewSpacing:(NSInteger)thumbViewSpacing withLabel:(BOOL)withLabel loaderInnerViewColor:(NSArray<UIColor *> * _Nonnull)loaderInnerViewColor loaderColors:(NSArray<UIColor *> * _Nonnull)loaderColors loaderInnerViewWidth:(NSInteger)loaderInnerViewWidth loaderWidth:(NSInteger)loaderWidth storyViewedIndicatorColor:(UIColor * _Nonnull)storyViewedIndicatorColor storyViewedIndicatorAlpha:(float)storyViewedIndicatorAlpha thumbViewOverlayColor:(UIColor * _Nonnull)thumbViewOverlayColor playerBackgroundColor:(UIColor * _Nonnull)playerBackgroundColor OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC14JoinStoriesSDK22StoryViewConfigDefault")
@interface StoryViewConfigDefault : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) StoryViewConfigDefault * _Nonnull shared;)
+ (StoryViewConfigDefault * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// The default timeout for each request is 60 seconds.
@property (nonatomic, readonly) NSTimeInterval requestTimeoutInterval;
@property (nonatomic, readonly) NSInteger containerDimension;
@property (nonatomic, readonly, copy) NSString * _Nonnull fontName;
@property (nonatomic, readonly, strong) UIColor * _Nonnull labelColor;
@property (nonatomic, readonly) NSInteger thumbViewSpacing;
@property (nonatomic, readonly) BOOL withLabel;
@property (nonatomic, readonly, copy) NSArray<UIColor *> * _Nonnull loaderInnerViewColor;
@property (nonatomic, readonly, copy) NSArray<UIColor *> * _Nonnull loaderColors;
@property (nonatomic, readonly) NSInteger loaderInnerViewWidth;
@property (nonatomic, readonly) NSInteger loaderWidth;
@property (nonatomic, readonly, strong) UIColor * _Nonnull storyViewedIndicatorColor;
@property (nonatomic, readonly) float storyViewedIndicatorAlpha;
@property (nonatomic, readonly, strong) UIColor * _Nonnull thumbViewOverlayColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull playerBackgroundColor;
@property (nonatomic, readonly) BOOL playerShowShareButton;
@property (nonatomic, readonly) NSInteger playerHorizontalMargins;
@property (nonatomic, readonly) NSInteger playerCornerRadius;
@end












#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
#ifndef JOINSTORIESSDK_SWIFT_H
#define JOINSTORIESSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="JoinStoriesSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;

SWIFT_CLASS("_TtC14JoinStoriesSDK17JoinConfiguration")
@interface JoinConfiguration : NSObject
- (nonnull instancetype)initWithTeam:(NSString * _Nonnull)team OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14JoinStoriesSDK11JoinStories")
@interface JoinStories : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) JoinStories * _Nonnull shared;)
+ (JoinStories * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (void)setConfiguration:(JoinConfiguration * _Nonnull)configuration;
+ (void)stopPlayer;
- (void)stopPlayer;
@end

@class UIColor;
enum PlayerVerticalAnchor : NSInteger;

SWIFT_PROTOCOL("_TtP14JoinStoriesSDK17JoinStoriesConfig_")
@protocol JoinStoriesConfig
@property (nonatomic, copy) NSString * _Nonnull alias;
@property (nonatomic) NSTimeInterval requestTimeoutInterval;
@property (nonatomic, strong) UIColor * _Nonnull playerBackgroundColor;
@property (nonatomic) enum PlayerVerticalAnchor playerVerticalAnchor;
@property (nonatomic) BOOL playerShowShareButton;
@property (nonatomic) NSInteger playerHorizontalMargins;
@property (nonatomic) NSInteger playerCornerRadius;
@property (nonatomic, copy) NSString * _Nullable playerProgressBarDefaultColor;
@property (nonatomic, copy) NSString * _Nullable playerProgressBarFillColor;
@property (nonatomic) NSInteger playerProgressBarThickness;
@property (nonatomic) NSInteger playerProgressBarRadius;
@end

enum PlayerStandaloneAnimationOrigin : NSInteger;

SWIFT_CLASS("_TtC14JoinStoriesSDK27JoinStoriesStandaloneConfig")
@interface JoinStoriesStandaloneConfig : NSObject <JoinStoriesConfig>
@property (nonatomic, copy) NSString * _Nonnull alias;
@property (nonatomic) NSTimeInterval requestTimeoutInterval;
@property (nonatomic, strong) UIColor * _Nonnull playerBackgroundColor;
@property (nonatomic) enum PlayerVerticalAnchor playerVerticalAnchor;
@property (nonatomic) BOOL playerShowShareButton;
@property (nonatomic) NSInteger playerHorizontalMargins;
@property (nonatomic) NSInteger playerCornerRadius;
@property (nonatomic, copy) NSString * _Nullable playerProgressBarDefaultColor;
@property (nonatomic, copy) NSString * _Nullable playerProgressBarFillColor;
@property (nonatomic) NSInteger playerProgressBarThickness;
@property (nonatomic) NSInteger playerProgressBarRadius;
- (nonnull instancetype)initWithAlias:(NSString * _Nonnull)alias requestTimeoutInterval:(NSTimeInterval)requestTimeoutInterval playerBackgroundColor:(UIColor * _Nonnull)playerBackgroundColor playerStandaloneAnimationOrigin:(enum PlayerStandaloneAnimationOrigin)playerStandaloneAnimationOrigin playerVerticalAnchor:(enum PlayerVerticalAnchor)playerVerticalAnchor playerShowShareButton:(BOOL)playerShowShareButton playerHorizontalMargins:(NSInteger)playerHorizontalMargins playerCornerRadius:(NSInteger)playerCornerRadius playerProgressBarDefaultColor:(NSString * _Nullable)playerProgressBarDefaultColor playerProgressBarFillColor:(NSString * _Nullable)playerProgressBarFillColor playerProgressBarThickness:(NSInteger)playerProgressBarThickness playerProgressBarRadius:(NSInteger)playerProgressBarRadius OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14JoinStoriesSDK34JoinStoriesStandaloneDefaultConfig")
@interface JoinStoriesStandaloneDefaultConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) JoinStoriesStandaloneDefaultConfig * _Nonnull shared;)
+ (JoinStoriesStandaloneDefaultConfig * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14JoinStoriesSDK22JoinStoriesThumbConfig")
@interface JoinStoriesThumbConfig : NSObject <JoinStoriesConfig>
@property (nonatomic, copy) NSString * _Nonnull alias;
@property (nonatomic) NSTimeInterval requestTimeoutInterval;
@property (nonatomic, strong) UIColor * _Nonnull playerBackgroundColor;
@property (nonatomic) enum PlayerVerticalAnchor playerVerticalAnchor;
@property (nonatomic) BOOL playerShowShareButton;
@property (nonatomic) NSInteger playerHorizontalMargins;
@property (nonatomic) NSInteger playerCornerRadius;
@property (nonatomic, copy) NSString * _Nullable playerProgressBarDefaultColor;
@property (nonatomic, copy) NSString * _Nullable playerProgressBarFillColor;
@property (nonatomic) NSInteger playerProgressBarThickness;
@property (nonatomic) NSInteger playerProgressBarRadius;
- (nonnull instancetype)initWithAlias:(NSString * _Nonnull)alias requestTimeoutInterval:(NSTimeInterval)requestTimeoutInterval containerDimension:(NSInteger)containerDimension fontName:(NSString * _Nonnull)fontName labelColor:(UIColor * _Nonnull)labelColor thumbViewSpacing:(NSInteger)thumbViewSpacing withLabel:(BOOL)withLabel loaderInnerViewColor:(NSArray<UIColor *> * _Nonnull)loaderInnerViewColor loaderColors:(NSArray<UIColor *> * _Nonnull)loaderColors loaderInnerViewWidth:(NSInteger)loaderInnerViewWidth loaderWidth:(NSInteger)loaderWidth storyViewedIndicatorColor:(UIColor * _Nonnull)storyViewedIndicatorColor storyViewedIndicatorAlpha:(float)storyViewedIndicatorAlpha thumbViewOverlayColor:(UIColor * _Nonnull)thumbViewOverlayColor playerBackgroundColor:(UIColor * _Nonnull)playerBackgroundColor playerVerticalAnchor:(enum PlayerVerticalAnchor)playerVerticalAnchor playerShowShareButton:(BOOL)playerShowShareButton playerHorizontalMargins:(NSInteger)playerHorizontalMargins playerCornerRadius:(NSInteger)playerCornerRadius playerProgressBarDefaultColor:(NSString * _Nullable)playerProgressBarDefaultColor playerProgressBarFillColor:(NSString * _Nullable)playerProgressBarFillColor playerProgressBarThickness:(NSInteger)playerProgressBarThickness playerProgressBarRadius:(NSInteger)playerProgressBarRadius OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM(NSInteger, PlayerStandaloneAnimationOrigin, open) {
  PlayerStandaloneAnimationOriginDefault = 0,
  PlayerStandaloneAnimationOriginTop = 1,
  PlayerStandaloneAnimationOriginTopLeft = 2,
  PlayerStandaloneAnimationOriginTopRight = 3,
  PlayerStandaloneAnimationOriginBottom = 4,
  PlayerStandaloneAnimationOriginBottomLeft = 5,
  PlayerStandaloneAnimationOriginBottomRight = 6,
};

typedef SWIFT_ENUM(NSInteger, PlayerVerticalAnchor, open) {
/// Anchor is expanded out of its safe area.
  PlayerVerticalAnchorTopIgnoringSafeArea = 0,
/// Anchor is considering its safe area.
  PlayerVerticalAnchorTopWithSafeArea = 1,
  PlayerVerticalAnchorBottom = 2,
  PlayerVerticalAnchorCenter = 3,
};

typedef SWIFT_ENUM(NSInteger, StoriesAPIError, open) {
  StoriesAPIErrorConfigurationNotFound = 0,
  StoriesAPIErrorConfigurationNoTeamFound = 1,
  StoriesAPIErrorNoData = 2,
  StoriesAPIErrorFetchingStoriesTimedOut = 3,
  StoriesAPIErrorFetchingStoriesFailed = 4,
  StoriesAPIErrorFetchingStoriesEmpty = 5,
};
static NSString * _Nonnull const StoriesAPIErrorDomain = @"JoinStoriesSDK.StoriesAPIError";


SWIFT_CLASS("_TtC14JoinStoriesSDK34StoryCircularInteractiveTransition")
@interface StoryCircularInteractiveTransition : UIPercentDrivenInteractiveTransition
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14JoinStoriesSDK23StoryCircularTransition")
@interface StoryCircularTransition : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol UIViewControllerContextTransitioning;

@interface StoryCircularTransition (SWIFT_EXTENSION(JoinStoriesSDK)) <UIViewControllerAnimatedTransitioning>
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> _Nullable)transitionContext SWIFT_WARN_UNUSED_RESULT;
- (void)animateTransition:(id <UIViewControllerContextTransitioning> _Nonnull)transitionContext;
@end

@class NSCoder;

SWIFT_CLASS("_TtC14JoinStoriesSDK23StoryCollectionViewCell")
@interface StoryCollectionViewCell : UICollectionViewCell
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForReuse;
@end

@class NSIndexPath;

SWIFT_PROTOCOL("_TtP14JoinStoriesSDK23StoryNavigationDelegate_")
@protocol StoryNavigationDelegate
/// Save as <code>seen</code> when navigating through stories
- (void)storyItemShownAt:(NSIndexPath * _Nonnull)indexPath;
@end

@class WKWebViewConfiguration;
@class WKUserContentController;
@class WKScriptMessage;

SWIFT_CLASS("_TtC14JoinStoriesSDK11StoryPlayer")
@interface StoryPlayer : WKWebView <WKScriptMessageHandler>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end



@class WKNavigation;
@class WKNavigationAction;
@class UIScrollView;
@class StoryValue;
@class NSBundle;

SWIFT_CLASS("_TtC14JoinStoriesSDK25StoryPlayerViewController")
@interface StoryPlayerViewController : UIViewController <WKNavigationDelegate>
@property (nonatomic) CGPoint startingPoint;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)onPlayerDismiss;
- (void)didReceiveNoPreviousPageListenerOn:(StoryValue * _Nonnull)story;
- (void)didReceiveNoNextPageListenerOn:(StoryValue * _Nonnull)story;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface StoryPlayerViewController (SWIFT_EXTENSION(JoinStoriesSDK)) <UIViewControllerTransitioningDelegate>
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed SWIFT_WARN_UNUSED_RESULT;
@end

@class UICollectionView;

@interface StoryPlayerViewController (SWIFT_EXTENSION(JoinStoriesSDK)) <UICollectionViewDataSource>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class UICollectionViewLayout;

@interface StoryPlayerViewController (SWIFT_EXTENSION(JoinStoriesSDK)) <UICollectionViewDelegateFlowLayout>
- (void)collectionView:(UICollectionView * _Nonnull)collectionView willDisplayCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


/// This class will inherit from NSObject and will implement the
/// UIViewControllerAnimatedTransitioning protocol for the transition from top to bottom
SWIFT_CLASS("_TtC14JoinStoriesSDK24StorySlideDownTransition")
@interface StorySlideDownTransition : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface StorySlideDownTransition (SWIFT_EXTENSION(JoinStoriesSDK)) <UIViewControllerAnimatedTransitioning>
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> _Nullable)transitionContext SWIFT_WARN_UNUSED_RESULT;
- (void)animateTransition:(id <UIViewControllerContextTransitioning> _Nonnull)transitionContext;
@end


/// This class will inherit from NSObject and will implement the
/// UIViewControllerAnimatedTransitioning protocol for the transition from bottom to top
SWIFT_CLASS("_TtC14JoinStoriesSDK22StorySlideUpTransition")
@interface StorySlideUpTransition : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface StorySlideUpTransition (SWIFT_EXTENSION(JoinStoriesSDK)) <UIViewControllerTransitioningDelegate>
@end


@interface StorySlideUpTransition (SWIFT_EXTENSION(JoinStoriesSDK)) <UIViewControllerAnimatedTransitioning>
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> _Nullable)transitionContext SWIFT_WARN_UNUSED_RESULT;
- (void)animateTransition:(id <UIViewControllerContextTransitioning> _Nonnull)transitionContext;
@end


SWIFT_CLASS("_TtC14JoinStoriesSDK14StoryThumbView")
@interface StoryThumbView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end



/// Used for custom transition
/// Implement UIViewControllerTransitioningDelegate`
/// See https://developer.apple.com/documentation/uikit/animation_and_haptics/view_controller_transitions
SWIFT_CLASS("_TtC14JoinStoriesSDK29StoryTransitionViewController")
@interface StoryTransitionViewController : UIViewController
/// Stories array to display
@property (nonatomic, copy) NSArray<StoryValue *> * _Nonnull stories;
/// Transition when displaying stories
/// Implement animations for our class
/// Conforms to <code>UIViewControllerAnimatedTransitioning</code> protocol
/// See https://developer.apple.com/documentation/uikit/uiviewcontrolleranimatedtransitioning
@property (nonatomic, strong) StoryCircularTransition * _Nonnull transition;
/// Interactive Transition when displaying stories
/// Inherits from <code>UIPercentDrivenInteractiveTransition</code>
/// See https://developer.apple.com/documentation/uikit/uipercentdriveninteractivetransition
@property (nonatomic, strong) StoryCircularInteractiveTransition * _Nonnull interactiveTransition;
/// StartingPoint from where the transition begins
/// With CollectionView, startingPoint correspond to center of the <code>collectionViewCell</code>
@property (nonatomic) CGPoint startingPoint;
/// CollectionView used to display thumbnails
/// Init CollectionView with <code>collectionViewLayout</code> and register to <code>StoryCollectionViewCell</code>
/// Should implement <code>UICollectionViewDelegate</code>
@property (nonatomic, strong) UICollectionView * _Nonnull collectionView;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@interface StoryTransitionViewController (SWIFT_EXTENSION(JoinStoriesSDK)) <StoryNavigationDelegate>
- (void)storyItemShownAt:(NSIndexPath * _Nonnull)indexPath;
@end


@interface StoryTransitionViewController (SWIFT_EXTENSION(JoinStoriesSDK)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@protocol UIViewControllerInteractiveTransitioning;

@interface StoryTransitionViewController (SWIFT_EXTENSION(JoinStoriesSDK)) <UIViewControllerTransitioningDelegate>
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerInteractiveTransitioning> _Nullable)interactionControllerForDismissal:(id <UIViewControllerAnimatedTransitioning> _Nonnull)animator SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14JoinStoriesSDK10StoryValue")
@interface StoryValue : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14JoinStoriesSDK15StoryViewConfig")
@interface StoryViewConfig : NSObject
- (nonnull instancetype)initWithRequestTimeoutInterval:(NSTimeInterval)requestTimeoutInterval containerDimension:(NSInteger)containerDimension fontName:(NSString * _Nonnull)fontName labelColor:(UIColor * _Nonnull)labelColor thumbViewSpacing:(NSInteger)thumbViewSpacing withLabel:(BOOL)withLabel loaderInnerViewColor:(NSArray<UIColor *> * _Nonnull)loaderInnerViewColor loaderColors:(NSArray<UIColor *> * _Nonnull)loaderColors loaderInnerViewWidth:(NSInteger)loaderInnerViewWidth loaderWidth:(NSInteger)loaderWidth storyViewedIndicatorColor:(UIColor * _Nonnull)storyViewedIndicatorColor storyViewedIndicatorAlpha:(float)storyViewedIndicatorAlpha thumbViewOverlayColor:(UIColor * _Nonnull)thumbViewOverlayColor playerBackgroundColor:(UIColor * _Nonnull)playerBackgroundColor OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC14JoinStoriesSDK22StoryViewConfigDefault")
@interface StoryViewConfigDefault : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) StoryViewConfigDefault * _Nonnull shared;)
+ (StoryViewConfigDefault * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// The default timeout for each request is 60 seconds.
@property (nonatomic, readonly) NSTimeInterval requestTimeoutInterval;
@property (nonatomic, readonly) NSInteger containerDimension;
@property (nonatomic, readonly, copy) NSString * _Nonnull fontName;
@property (nonatomic, readonly, strong) UIColor * _Nonnull labelColor;
@property (nonatomic, readonly) NSInteger thumbViewSpacing;
@property (nonatomic, readonly) BOOL withLabel;
@property (nonatomic, readonly, copy) NSArray<UIColor *> * _Nonnull loaderInnerViewColor;
@property (nonatomic, readonly, copy) NSArray<UIColor *> * _Nonnull loaderColors;
@property (nonatomic, readonly) NSInteger loaderInnerViewWidth;
@property (nonatomic, readonly) NSInteger loaderWidth;
@property (nonatomic, readonly, strong) UIColor * _Nonnull storyViewedIndicatorColor;
@property (nonatomic, readonly) float storyViewedIndicatorAlpha;
@property (nonatomic, readonly, strong) UIColor * _Nonnull thumbViewOverlayColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull playerBackgroundColor;
@property (nonatomic, readonly) BOOL playerShowShareButton;
@property (nonatomic, readonly) NSInteger playerHorizontalMargins;
@property (nonatomic, readonly) NSInteger playerCornerRadius;
@end












#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
